[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel_css_node"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
serde_bytes = "0.11.5"
serde_json = "*"
cssparser = "0.29.1"
parcel_css = { path = "../" }
parcel_sourcemap = "2.0.2"

[target.'cfg(target_os = "macos")'.dependencies]
jemallocator = { version = "0.3.2", features = ["disable_initial_exec_tls"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-trait = "0.1.53"
callback-future = "0.1"
futures = "0.3.21"
napi = {version = "2.2.0", default-features = false, features = ["napi5", "compat-mode", "serde-json", "tokio_rt"]}
napi-derive = "2"
tokio = {version = "1.19.0", features = ["rt", "rt-multi-thread"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
serde-wasm-bindgen = "0.3.0"
wasm-bindgen = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
napi-build = "1"
